spring.application.name=seguridad-api

# ============================================
# POSTGRESQL CONFIGURATION
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/mi_app_db
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============================================
# JWT CONFIGURATION
# ============================================
jwt.secret=${JWT_SECRET:miClaveSecretaSuperSegura1234567890}
jwt.expiration=86400000
jwt.issuer=seguridad-api

# ============================================
# KEYS PATH
# ============================================
jwt.private-key-path=keys/private_key.pem
jwt.public-key-path=keys/public_key.pem

# ============================================
# SWAGGER
# ============================================
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

server.port = 8081

# Forzar escaneo de repositorios
spring.data.jpa.repositories.bootstrap-mode=default

jwt.expiration=86400000
jwt.issuer=seguridad-api